dist: bionic
env:
    global:
    -   GIT_NAME: Dead-Hosts
    -   GIT_EMAIL: dead-hosts@outlook.com
    -   GIT_BRANCH: master
    -   secure: XKWIVAMDgzzsC9NkWTakV5aJN/w4JvLQ0Qsb6Hzu7J+5/RFyCfuCB16cF6XZY6oNi6XZcillZbG1d57vQmOfZ61KeTWlmqbi0Vqo8kCN7rWmBf+WD6zeb0aZnSaK+oLaKAVY/hhwd2iGifUWVGIFFQXcXsoBrMd57b2jyfiTzv5nTe74uddFu1la8c+K/olgi+9BXyxR0uvIJnpwwPvmejzi5ozGPfRwt5VjJDOw5e+w1RK+qWTXkerw3eVPnDM4ebDtclM6YJvR+q+lkhhL52HEdm7liS+t5l7q3Ykz+e6kXDYF/Bm0jsdH6QTSGbW2XoAKTEJXmpJ0o/S+Vbnf1mPnZOR62POq1GfbBlKj3ezs1HMmh5p5LRID5uz23Ww0WUzQ7DJ61K5BbW479KR139lKWVXtxRg2TS3EBWzROfikF/oq7zKcPkjRBHIubyLqnJ+9pCJ12HIp3tsEFFIVKz7IrmuVuYbbUtbectPhrGnj/cVs1IMUpM1GCBUHxbA8Dqs8QK7z0rM+QT0MAiWPiXdsf3Z45jk1FKpa0JjL2qCjZfxZraSqDf5uzNxWimaGrBHtP0WDwPCJmr0vAiTFTa1MDF90l+SpnIdH7q//Fihl7aM4Z4PMSMKHsOH/ylh+0a0DVGTLv764OMwj956xIXOuuZXeRcg8uIo7Cjlla08=
    -   PYTHON_VERSION: 3.7.5
install:
- export PATH="${HOME}/miniconda/bin:${PATH}"
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p ${HOME}/miniconda
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n launcher-environment python="${PYTHON_VERSION}"
- source activate launcher-environment
- python -VV
- pip --version
- pip install --upgrade dead-hosts-launcher
- rm miniconda.sh
language: generic
notifications:
    email:
        on_failure: always
        on_success: change
        recipients:
        - dead-hosts@outlook.com
os:
- linux
script:
- dead_hosts_launcher --version
- dead_hosts_launcher
